services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../:/app
    ports:
      - "5001:5000"
    depends_on:
      - db
      - rabbitmq
      - mongodb
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: admin
      DATABASE_PASSWORD: password
      DATABASE_NAME: EZAI_nosql
      # DATABASE_URI: postgresql://admin:password@db:5432/postgres
      DATABASE_URI: mongodb://localhost:27017/EZAI_nosql
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      AWS_DEFAULT_REGION: ap-southeast-1
      SQLALCHEMY_TRACK_MODIFICATIONS: False
    platform: linux/x86_64

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
