services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../:/app
    ports:
      - "5001:5000"
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URI: mongodb://mongodb:27017/EZAI_nosql  # Use 'mongodb' instead of 'localhost'
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      AWS_DEFAULT_REGION: ap-southeast-1
    platform: linux/x86_64

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
