services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../:/app
    ports:
      - "80:5000"
    depends_on:
      - rabbitmq
    environment:
      DATABASE_HOST: ezai-db.cmbu3xbjbxb4.us-east-1.rds.amazonaws.com
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: EZAI
      DATABASE_URI: postgresql://postgres:password@ezai-db.cmbu3xbjbxb4.us-east-1.rds.amazonaws.com:5432/EZAI
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      AWS_DEFAULT_REGION: ap-southeast-1
      SQLALCHEMY_TRACK_MODIFICATIONS": False
    platform: linux/x86_64

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
